// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBso7-LcK8SCkMSXPhzk17vGOYxcZbFqLM',
    appId: '1:659759344852:web:f4d3e1550207fcb18bdf41',
    messagingSenderId: '659759344852',
    projectId: 'shopappdelivery-fd552',
    authDomain: 'shopappdelivery-fd552.firebaseapp.com',
    storageBucket: 'shopappdelivery-fd552.appspot.com',
    measurementId: 'G-7BCGGCSVRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF1FVw5Fw5qZIS-JEobzAYxiDKtbB3Cos',
    appId: '1:659759344852:android:dcb6ebfc1e73defa8bdf41',
    messagingSenderId: '659759344852',
    projectId: 'shopappdelivery-fd552',
    storageBucket: 'shopappdelivery-fd552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdujvAgK9ccxRU_r4-hjEWbFeYVHVBvVY',
    appId: '1:659759344852:ios:d83847adfa3ee4ee8bdf41',
    messagingSenderId: '659759344852',
    projectId: 'shopappdelivery-fd552',
    storageBucket: 'shopappdelivery-fd552.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdujvAgK9ccxRU_r4-hjEWbFeYVHVBvVY',
    appId: '1:659759344852:ios:d83847adfa3ee4ee8bdf41',
    messagingSenderId: '659759344852',
    projectId: 'shopappdelivery-fd552',
    storageBucket: 'shopappdelivery-fd552.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBso7-LcK8SCkMSXPhzk17vGOYxcZbFqLM',
    appId: '1:659759344852:web:411518c7d8c21adf8bdf41',
    messagingSenderId: '659759344852',
    projectId: 'shopappdelivery-fd552',
    authDomain: 'shopappdelivery-fd552.firebaseapp.com',
    storageBucket: 'shopappdelivery-fd552.appspot.com',
    measurementId: 'G-BK692X2ZFC',
  );
}
